name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@ac85bc1e407e34e8be282ea4ba6c1b56dc56d172
        with:
          runCmd: ./build.sh
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - run: |
          dotnet nuget push ./packages/*.nupkg \
            --skip-duplicate \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            --api-key ${{ github.token }}
